### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by QC17551** [jianhuupenn/ItClust#16]
run `clf.adata_test.obsm['X_umap']=clf.Umap()` will make a mistake

`Traceback (most recent call last):
  File "D:/CODE_FILES/pythonProject/main.py", line 67, in <module>
    clf.adata_test.obsm['X_umap']=clf.Umap()
  File "D:\ProgramData\Anaconda3\envs\ItClust\lib\site-packages\itclust-1.2.0-py3.6.egg\ItClust\ItClust.py", line 240, in Umap
  File "D:\ProgramData\Anaconda3\envs\ItClust\lib\site-packages\scanpy\tools\_umap.py", line 173, in umap
    verbose=settings.verbosity > 3,
TypeError: simplicial_set_embedding() missing 3 required positional arguments: 'densmap', 'densmap_kwds', and 'output_dens'`

**Comment by jianhuupenn** [comment]
Please double-check the supporting packages' version, especially for scanpy and UMAP.
