### ISSUE TITLE
IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by mydkzgj** [jianhuupenn/ItClust#6]
Hi,

Thank you for your excellent work, I have implement it on many datasets sucessfully with baron-human as the source data. However, when I deal with the dataset "muraro", it ends up with an error. Here are details.

The debug information:
```
adata_source
AnnData object with n_obs × n_vars = 8569 × 16359
    obs: 'celltype'
adata_target
AnnData object with n_obs × n_vars = 2126 × 17577
    obs: 'celltype'
```

The output:
```
Using TensorFlow backend.
/home/yanhan/.conda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/yanhan/.conda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/yanhan/.conda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/yanhan/.conda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/yanhan/.conda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/yanhan/.conda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/yanhan/.conda/envs/tensorflow/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/yanhan/.conda/envs/tensorflow/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/yanhan/.conda/envs/tensorflow/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/yanhan/.conda/envs/tensorflow/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/yanhan/.conda/envs/tensorflow/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/yanhan/.conda/envs/tensorflow/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/yanhan/.conda/envs/tensorflow/lib/python3.6/site-packages/scanpy/api/__init__.py:6: FutureWarning: 

In a future version of Scanpy, `scanpy.api` will be removed.
Simply use `import scanpy as sc` and `import scanpy.external as sce` instead.

  FutureWarning,
WARNING:tensorflow:From method/ItClust-train.py:5: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

/home/yanhan/.conda/envs/tensorflow/lib/python3.6/site-packages/scanpy/preprocessing/_simple.py:297: DeprecationWarning: Use is_view instead of isview, isview will be removed in the future.
  if isinstance(data, AnnData) and data.isview:
the var_names of adata.raw: adata.raw.var_names.is_unique=: True
/home/yanhan/.conda/envs/tensorflow/lib/python3.6/site-packages/scanpy/preprocessing/_simple.py:297: DeprecationWarning: Use is_view instead of isview, isview will be removed in the future.
  if isinstance(data, AnnData) and data.isview:
/home/yanhan/.conda/envs/tensorflow/lib/python3.6/site-packages/scanpy/_utils.py:342: DeprecationWarning: Use is_view instead of isview, isview will be removed in the future.
  if adata.isview:
/home/yanhan/.conda/envs/tensorflow/lib/python3.6/site-packages/scanpy/preprocessing/_simple.py:297: DeprecationWarning: Use is_view instead of isview, isview will be removed in the future.
  if isinstance(data, AnnData) and data.isview:
the var_names of adata.raw: adata.raw.var_names.is_unique=: True
/home/yanhan/.conda/envs/tensorflow/lib/python3.6/site-packages/scanpy/preprocessing/_simple.py:297: DeprecationWarning: Use is_view instead of isview, isview will be removed in the future.
  if isinstance(data, AnnData) and data.isview:
/home/yanhan/.conda/envs/tensorflow/lib/python3.6/site-packages/scanpy/_utils.py:342: DeprecationWarning: Use is_view instead of isview, isview will be removed in the future.
  if adata.isview:
Traceback (most recent call last):
  File "method/ItClust-train.py", line 99, in <module>
    train(root_path, dataset_name, save_path)
  File "method/ItClust-train.py", line 66, in train
    clf.fit(adata_source, adata_target)
  File "/home/yanhan/.conda/envs/tensorflow/lib/python3.6/site-packages/ItClust/ItClust.py", line 112, in fit
    full_adata=AnnData.concatenate(*adata_tmp,join='inner',batch_key="dataset_batch",batch_categories=["source","target"]) #inner
  File "/home/yanhan/.conda/envs/tensorflow/lib/python3.6/site-packages/anndata/_core/anndata.py", line 1727, in concatenate
    partial(merge_outer, batch_keys=batch_categories, merge=merge_same),
  File "/home/yanhan/.conda/envs/tensorflow/lib/python3.6/site-packages/anndata/_core/anndata.py", line 857, in var
    self._set_dim_df(value, "var")
  File "/home/yanhan/.conda/envs/tensorflow/lib/python3.6/site-packages/anndata/_core/anndata.py", line 783, in _set_dim_df
    value_idx = self._prep_dim_index(value.index, attr)
  File "/home/yanhan/.conda/envs/tensorflow/lib/python3.6/site-packages/anndata/_core/anndata.py", line 810, in _prep_dim_index
    value[0], (str, bytes)
  File "/home/yanhan/.conda/envs/tensorflow/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 4104, in __getitem__
    return getitem(key)
IndexError: index 0 is out of bounds for axis 0 with size 0
```

It seems like an error in AnnData.concatenate(), but the cause is unclear for me.

**Comment by jianhuupenn** [comment]
Could you check the index of your AnnData? I think I have a similar issue when I get the wrong index formal (a 0 in index name). 
I think I solved my problem using something like:
adata.obs.index=adata.obs.index.tolist()

**Comment by mydkzgj** [comment]
Well, thank you for your reply. I conduct an experiment and find the reason is actually the source and target datasets (after preprocessed) do not have a same gene inside, so that they can not be concatenated under the "inner" mode. 

I am also wondering that if we should look for different similar source datasets for different target datasets, or build a large combined dataset for general target datasets?

**Comment by jianhuupenn** [comment]
Sorry for the late reply, I think it is better to build a large combined dataset with comprehensive cell types. One thing to notice is that, for cell types presented in multiple datasets, I would prefer using them from only one dataset to avoid batch effect. For example, dataset1 has cell types A, B and C, dataset2 has cell types C and D. I would exclude cell type C from dataset2 before combining.

**Comment by mydkzgj** [comment]
Thanks for your valuable suggestion！
