### ISSUE TITLE
RuntimeError: Python version >= 3.7 required.

### ISSUE THREAD

**Issue by bitcometz** [jianhuupenn/ItClust#7]
hi，
I try to install ItClust by the flowing approach: 
```
# create an environment called ItClust
conda create -n ItClust python=3.5.3
# activate your environment 
conda activate ItClust
git clone https://github.com/jianhuupenn/ItClust
cd ItClust/ItClust_package/
python3 setup.py build
python3 setup.py install
```
The only difference is tha I install `miniconda` instead of `Anaconda `.

When I run `python3 setup.py install`, I got the errro info:
```
Installed /Users/liji/miniconda3/envs/ItClust/lib/python3.5/site-packages/scanpy-1.7.2-py3.5.egg
Searching for scipy
Reading https://pypi.org/simple/scipy/
Downloading https://files.pythonhosted.org/packages/fe/fd/8704c7b7b34cdac850485e638346025ca57c5a859934b9aa1be5399b33b7/scipy-1.6.3.tar.gz#sha256=a75b014d3294fce26852a9d04ea27b5671d86736beb34acdfc05859246260707
Best match: scipy 1.6.3
Processing scipy-1.6.3.tar.gz
Writing /var/folders/gq/xxxc8g4n1z74zxv564v3zs6c0000gn/T/easy_install-gkw9qnoh/scipy-1.6.3/setup.cfg
Running scipy-1.6.3/setup.py -q bdist_egg --dist-dir /var/folders/gq/xxxc8g4n1z74zxv564v3zs6c0000gn/T/easy_install-gkw9qnoh/scipy-1.6.3/egg-dist-tmp-oeotxfvb
Traceback (most recent call last):
  File "/Users/liji/miniconda3/envs/ItClust/lib/python3.5/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/Users/liji/miniconda3/envs/ItClust/lib/python3.5/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/Users/liji/miniconda3/envs/ItClust/lib/python3.5/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/Users/liji/miniconda3/envs/ItClust/lib/python3.5/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/var/folders/gq/xxxc8g4n1z74zxv564v3zs6c0000gn/T/easy_install-gkw9qnoh/scipy-1.6.3/setup.py", line 31, in <module>
RuntimeError: Python version >= 3.7 required.
```

Could you help with this problem? 

Thanks !!!

**Comment by jianhuupenn** [comment]
I think the error comes from Python version. Instead of 
```
conda create -n ItClust python=3.5.3
```
could you change it to some python version higher than 3.7? for example,
```
conda create -n ItClust python=3.7.0 
```
or 3.7.5?

**Comment by bitcometz** [comment]
This is a great software. 
Thank you for your reply, I will try to see if it works~

**Comment by bitcometz** [comment]
It works now, but I have to install tensorflow:
```
pip install tensorflow==1.14.0
```

and I still got some errors:
```
import ItClust as ic
import scanpy.api as sc
import os
from numpy.random import seed
from tensorflow import set_random_seed
import pandas as pd
import numpy as np
import warnings
os.environ["CUDA_VISIBLE_DEVICES"]="1"
warnings.filterwarnings("ignore")
#import sys
#!{sys.executable} -m pip install 'scanpy==1.4.4.post1'
#Set seeds
seed(20180806)
np.random.seed(10)
set_random_seed(20180806) # on GPU may be some other default
```

```
ImportError                               Traceback (most recent call last)
<ipython-input-5-2f9b8107b829> in <module>
----> 1 import ItClust as ic
      2 import scanpy.api as sc
      3 import os
      4 from numpy.random import seed
      5 from tensorflow import set_random_seed

~/miniconda3/envs/ItClust/lib/python3.7/site-packages/ItClust-0.0.5-py3.7.egg/ItClust/__init__.py in <module>
      1 __version__ = '1.0.0'
----> 2 from . ItClust import transfer_learning_clf

~/miniconda3/envs/ItClust/lib/python3.7/site-packages/ItClust-0.0.5-py3.7.egg/ItClust/ItClust.py in <module>
      2 from time import time
      3 ####
----> 4 from . DEC import DEC
      5 from . preprocessing import *
      6 ####

~/miniconda3/envs/ItClust/lib/python3.7/site-packages/ItClust-0.0.5-py3.7.egg/ItClust/DEC.py in <module>
      2 import os
      3 
----> 4 from . SAE import SAE  # load Stacked autoencoder
      5 from . preprocessing import change_to_continuous
      6 from time import time

~/miniconda3/envs/ItClust/lib/python3.7/site-packages/ItClust-0.0.5-py3.7.egg/ItClust/SAE.py in <module>
----> 1 from keras.callbacks import TensorBoard, ModelCheckpoint, EarlyStopping, ReduceLROnPlateau,History
      2 from keras.layers import Input, Dense, Dropout
      3 from keras.models import Model, Sequential
      4 from keras.optimizers import SGD
      5 from keras.utils.vis_utils import plot_model

~/miniconda3/envs/ItClust/lib/python3.7/site-packages/keras-2.5.0rc0-py3.7.egg/keras/__init__.py in <module>
     23 
     24 # See b/110718070#comment18 for more details about this import.
---> 25 from keras import models
     26 
     27 from keras.engine.input_layer import Input

~/miniconda3/envs/ItClust/lib/python3.7/site-packages/keras-2.5.0rc0-py3.7.egg/keras/models.py in <module>
     17 
     18 import tensorflow.compat.v2 as tf
---> 19 from keras import backend
     20 from keras import metrics as metrics_module
     21 from keras import optimizer_v1

~/miniconda3/envs/ItClust/lib/python3.7/site-packages/keras-2.5.0rc0-py3.7.egg/keras/backend.py in <module>
     35 from tensorflow.python.distribute import distribute_coordinator as dc
     36 from tensorflow.python.distribute import distribute_coordinator_context as dc_context
---> 37 from tensorflow.python.eager.context import get_config
     38 from tensorflow.python.framework import config
     39 from keras import backend_config

ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context' (/Users/liji/miniconda3/envs/ItClust/lib/python3.7/site-packages/tensorflow/python/eager/context.py)
```

**Comment by bitcometz** [comment]
and I update to the versions in your provided enviroment, and it is ok now !
